language: node_js

node_js:
  - 12
  
cache:
  directories:
    - node_modules

script: npm run test:unit

after_script:
- npm install coveralls@3 && npm run specs && coveralls < coverage/lcov.info

after_success:
- npm run build


deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: develop
